household_power_consumption$Date <- as.Date(household_power_consumption$Date, format="%d/%m/%Y")
mydata<-subset(household_power_consumption, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
newdatetime <- within(mydata, { timestamp=format(as.POSIXct(paste(Date, Time)), "%Y-%m-%d %H:%M:%S") })
newdatetime$date_time <- strptime(newdatetime$timestamp, format="%Y-%m-%d %H:%M:%S")
attach(newdatetime)
png(file="Rplot3.png",width=480,height=480)
plot(date_time,Sub_metering_1, type="l", xlab="",ylab="Energy Sub Metering")
lines(date_time,Sub_metering_2, type="l", col="red")
lines(date_time,Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub Metering 1","Sub Metering 2", "Sub Metering 3"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","red","blue"))
dev.off()